### PR TITLE
feat: configure Docker registry settings

### PR DESCRIPTION
**Pull request by hknutsen**
## Changes

- Add properties `docker_registry_url`, `docker_registry_username` and `docker_registry_password` to variable `application_stack`.
- Add validation rule to variable `app_settings` to ensure Docker settings are configured using variable `application_stack` instead.
- Update `container-app` example to demonstrate configuration of Docker settings.

## Checklist

- [x] I've updated both the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

### CODE REVIEW

**Comment by hknutsen** [comment]
Consider removing `docker_registry_username` and `docker_registry_password` and enforce use of managed identity instead.

**Comment by hknutsen** [comment]
Investigate if it's possible to ignore changes to Docker-related app settings in `azapi_update_resource.app_settings`.

**Comment by hknutsen** [comment]
The refactoring of how app settings are configured has been moved into a separate PR that should be merged first: #167

**Comment by hknutsen** [comment]
Tests pass 🎉

**Review by stiross79 — APPROVED** [review]
looks good

**Pull request merged**
