### PR TITLE
fix: ignore changes to application logs

### PR DESCRIPTION
**Pull request by hknutsen**

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass 🎉

**Comment by hknutsen** [comment]
If this still does not work as expected, maybe consider remove application logs from this module, and add a comment stating that since application logs are a permanent feature, it should be enabled when needed.

**Comment by hknutsen** [comment]
I've created a web app using the linux-app example in this branch. Will run the same example tomorrow to see if terraform still wants to re-enable app logs.

**Comment by hknutsen** [comment]
Working as expected! 😄

**Review by sebastianlolv — APPROVED** [review]
Tests pass🥇

**Pull request merged**
