### PR TITLE
feat!: create multiple active directory auth settings

### LINKED ISSUE #48: feat: make azure ad authentication optional
Currently input variable `aad_client_id` is required, thus it is required to configure Azure AD authentication for a Web App created using this module. There are multiple other ways to implement Azure AD auth in your app, thus this should be optional in this module, in case Azure AD auth is to be implemented using another method.

### PR DESCRIPTION
**Pull request by hknutsen**
Closes #48

### CODE REVIEW

**Comment by hknutsen** [comment]
One step closer to the baseline.

**Comment by hknutsen** [comment]
Tests pass 🎉

**Review by sebastianlolv — APPROVED** [review]
Looks good 👍

**Review by helenakallekleiv — APPROVED** [review]
Looks good 👍🏼

**Pull request merged**
