### PR TITLE
feat!: create multiple diagnostic settings

### PR DESCRIPTION
**Pull request by hknutsen**
Allow creation of multiple diagnostic settings if needed.

Enforce creation of at least one diagnostic setting to keep same default behaviour as before.

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass 🎉

**Comment by hknutsen** [comment]
@sebastianlolv @helenakallekleiv @kov117 Any thoughts on how I've implemented this?

**Comment by kov117** [comment]
I think it looks great 💯 i think this is a great way to implement multiple diagnostic settings, looks more efficient and easier way to handle 👍🏽

**Comment by helenakallekleiv** [comment]
@hknutsen Implementation looks good, I'm just wondering how many other types of diagnostic settings is availiable, other than `"audit-logs"`? E.g. in what scenario would we need more than audit logs?

**Comment by hknutsen** [comment]
@helenakallekleiv That's sort of why I'm asking for feedback. In most scenarios you'll only need audit logs. If you ever have a scenario where you'd need other types of logs, you could always create a separate diagnostic setting outside of this module.

So I think maybe just keep the module as is, i.e. creating only a single diagnostic setting, to keep the simplicity of the current implementation.

**Pull request closed without merging**
