### PR TITLE
chore: application stack arguments are set outside of config

### PR DESCRIPTION
**Pull request by helenakallekleiv**
### Checklist

- [x] I've updated both the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

### CODE REVIEW

**Comment by helenakallekleiv** [comment]
All tests pass

**Review by kov117 — DISMISSED** [review]
👍🏽

**Comment by helenakallekleiv** [comment]
After some digging, we've concluded that the `application_stack` block and nested arguments should be omitted from infra config, and is rather being set during application deployment.

Added a comment in `main.tf`, outlining this.

**Review by hknutsen — APPROVED** [review]
Looks good 🎉

**Pull request merged**
