### PR TITLE
feat!: enable app logs and diagnostics

### LINKED ISSUE #37: feat: add diagnostic setting
Add a diagnostic setting to record audit logs for the web app.

### PR DESCRIPTION
**Pull request by helenakallekleiv**
Enable application logs  for Azure Web App, and send diagnostics to Azure Monitor.

Closes #37, closes #18

### CODE REVIEW

**Comment by helenakallekleiv** [comment]
Go tests passed on my local machine.

**Comment by hknutsen** [comment]
Consider enabling [app logs](https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enable-application-logging-windows) as well.

**Comment by helenakallekleiv** [comment]
Go test passed on my local machine for all examples (`container`, `windows` and `linux`).

**Review by sebastianlolv — APPROVED** [review]
Passes tests on my machine too.

**Pull request merged**
